#pragma once

#include <cfenv>
#include <cstdlib>
#include <cmath>
#include <cassert>
#include <cstring>
#include <cctype>
#include <cwchar>

#include <iostream>
#include <fstream>
#include <memory>
#include <exception>
#include <stdexcept>
#include <mutex>
#include <thread>
#include <future>
#include <any>
#include <sstream>
#include <string>
#include <bitset>
#include <array>
#include <deque>
#include <forward_list>
#include <list>
#include <map>
#include <queue>
#include <set>
#include <stack>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <system_error>
#include <regex>
#include <new>
#include <random>
#include <ratio>
#include <tuple>
#include <initializer_list>
#include <iterator>
#include <limits>
#include <locale>
#include <algorithm>
#include <functional>
#include <utility>
#include <type_traits>
#include <valarray>
#include <typeinfo>
#include <typeindex>
#include <chrono>
